# .github/release-drafter.yml
name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
version-template: "$MAJOR.$MINOR.$PATCH"

categories:
  - title: "Mobile App"
    labels:
      - "mobile"
  - title: "Web Admin"
    labels:
      - "web"
  - title: "Shared Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "Bug Fixes"
    labels:
      - "bug"
      - "fix"
  - title: "Maintenance"
    labels:
      - "chore"
      - "docs"
      - "refactor"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  ## Changes
  $CHANGES

  ## Contributors
  $CONTRIBUTORS