// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBlWVSua4QfPefy4TRPmOT_7ErfgAuZZ4',
    appId: '1:739021537990:web:e3804e106daad32cfe0dc7',
    messagingSenderId: '739021537990',
    projectId: 'doughboyspizzeria-2b3d2',
    authDomain: 'doughboyspizzeria-2b3d2.firebaseapp.com',
    storageBucket: 'doughboyspizzeria-2b3d2.firebasestorage.app',
    measurementId: 'G-SJRBLVVV5Z',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHNR08G23pWXP7kg1nSGC-LETf0rpgLis',
    appId: '1:739021537990:ios:bd55027d8875c8befe0dc7',
    messagingSenderId: '739021537990',
    projectId: 'doughboyspizzeria-2b3d2',
    storageBucket: 'doughboyspizzeria-2b3d2.firebasestorage.app',
    androidClientId: '739021537990-jlf0rrei7f54l35fp9ngjpo1lm95tje4.apps.googleusercontent.com',
    iosClientId: '739021537990-dmafgo3h5bokvs2gceithf8eb16jvnt4.apps.googleusercontent.com',
    iosBundleId: 'com.example.doughboysPizzeriaFresh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBlWVSua4QfPefy4TRPmOT_7ErfgAuZZ4',
    appId: '1:739021537990:web:5d0151f63aee60a1fe0dc7',
    messagingSenderId: '739021537990',
    projectId: 'doughboyspizzeria-2b3d2',
    authDomain: 'doughboyspizzeria-2b3d2.firebaseapp.com',
    storageBucket: 'doughboyspizzeria-2b3d2.firebasestorage.app',
    measurementId: 'G-NBBQLGS25D',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHNR08G23pWXP7kg1nSGC-LETf0rpgLis',
    appId: '1:739021537990:ios:bd55027d8875c8befe0dc7',
    messagingSenderId: '739021537990',
    projectId: 'doughboyspizzeria-2b3d2',
    storageBucket: 'doughboyspizzeria-2b3d2.firebasestorage.app',
    androidClientId: '739021537990-2o9k7gke4ijuio0vg760oteg1mrk6a4e.apps.googleusercontent.com',
    iosClientId: '739021537990-dmafgo3h5bokvs2gceithf8eb16jvnt4.apps.googleusercontent.com',
    iosBundleId: 'com.example.doughboysPizzeriaFresh',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyEWoMyMkLD6qHmuqMQt0EvloVdFqK8Vg',
    appId: '1:739021537990:android:43d49458c788c07ffe0dc7',
    messagingSenderId: '739021537990',
    projectId: 'doughboyspizzeria-2b3d2',
    storageBucket: 'doughboyspizzeria-2b3d2.firebasestorage.app',
  );

}


