name: admin_portal
description: A Flutter web app for franchise administration
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  firebase_analytics: ^11.4.6
  firebase_messaging: ^15.2.6
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  dropdown_search: ^5.0.6
  carousel_slider: ^5.0.0
  path: ^1.9.0
  logging: ^1.2.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.6
  shimmer: ^3.0.0
  logger: ^2.0.2
  path_provider: ^2.1.2
  intl: 0.19.0
  uuid: ^4.0.0
  cached_network_image: ^3.3.1
  file_picker: ^6.1.1
  file_saver: ^0.2.4
  fl_chart: ^0.65.0
  async: ^2.11.0
  collection: ^1.18.0
  share_plus: ^7.2.2
  firebase_storage: ^12.4.6
  permission_handler: ^11.3.1
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  csv: ^5.0.2
  cloud_functions: ^5.6.1
  go_router: ^16.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl_utils: ^2.8.4
  test: ^1.20.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo.png
    - assets/images/logo_small.png
    - assets/images/logo_large.png
    - assets/images/banner_placeholder.png
    - assets/icons/
    - assets/images/avatar_placeholder.png
    - assets/images/default_profile.png
    - assets/images/menu_item_placeholder.png
    - assets/images/ingredient_placeholder.png
    - assets/images/admin_empty.png
    - assets/images/

flutter_icons:
  android: false
  ios: false
  image_path: "assets/images/logo.png"

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations
