# .github/workflows/build-mobile.yml
name: Build Mobile APK

on:
  push:
    branches: [ main ]
    paths:
      - 'mobile_app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mobile_app

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v3
        with:
          name: doughboys-app
          path: build/app/outputs/flutter-apk/app-release.apk